In [ ]:
import pandas as pd

In [2]:
file = 'Resources/netflix_titles.csv'

In [3]:
netflix_df=pd.read_csv(file, encoding="ISO-8859-1")

In [4]:
netflix_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"JoÃ£o Miguel, Bianca Comparato, Michel Gomes, ...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"DemiÃ¡n Bichir, HÃ©ctor Bonilla, Oscar Serrano...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [5]:
netflix_df=netflix_df.drop(['show_id','cast','date_added','rating','duration','listed_in','description'], axis=1)

In [6]:
netflix_df = netflix_df.rename(columns={"type":"Type","title":"Movie","director":"Director","country":"Country","release_year":"Year"})
netflix_df.head()

      Type  Movie           Director        Country  Year
0  TV Show     3%                NaN         Brazil  2020
1    Movie   7:19  Jorge Michel Grau         Mexico  2016
2    Movie  23:59       Gilbert Chan      Singapore  2011
3    Movie      9        Shane Acker  United States  2009
4    Movie     21     Robert Luketic  United States  2008

In [7]:
index_names=netflix_df[netflix_df["Type"]=="TV Show"].index
netflix_df.drop(index_names,inplace=True)

In [9]:
netflix_df.sample(20)

,Type,Movie,Director,Country,Year
1363,Movie,Christmas Crossfire,Detlev Buck,Germany,2020
5917,Movie,Surat Dari Praha,Angga Dwimas Sasongko,Indonesia,2016
737,Movie,Barbie in A Mermaid Tale,Adam Wood,United States,2010
1909,Movie,East Side Sushi,Anthony Lucero,United States,2015
4447,Movie,Neseli Hayat,YÄ±lmaz ErdoÄan,Turkey,2009
5847,Movie,Strike a Pose,"Ester Gould, Reijer Zwaan","Netherlands, Belgium",2016
7312,Movie,Una,Benedict Andrews,"United Kingdom, Canada, United States",2016
2379,Movie,Gerald's Game,Mike Flanagan,United States,2017
1919,Movie,Eddie Murphy: Raw,Robert Townsend,United States,1987
2948,Movie,Iliza Shlesinger: War Paint,Jay Chapman,United States,2013
5048,Movie,Raat Akeli Hai,Honey Trehan,India,2020
3937,Movie,Maria,Pedring A. Lopez,Philippines,2019
2336,Movie,Gagarin: First in Space,Pavel Parkhomenko,Russia,2013
362,Movie,AK vs AK,Vikramaditya Motwane,India,2020
590,Movie,Aruna & Her Palate,Edwin,"Indonesia, South Korea, Singapore",2018
4310,Movie,My Daddy is in Heaven,Waymon Boone,United States,2017
2819,Movie,Hot Gimmick: Girl Meets Boy,Yuki Yamato,Japan,2019
4045,Movie,Merku Thodarchi Malai,Lenin Bharathi,India,2018
6873,Movie,The Silent War,Alfonso CortÃ©s-Cavanillas,Spain,2020
3037,Movie,Inuyasha the Movie - L'isola del fuoco scarlatto,Toshiya Shinohara,Japan,2004

In [19]:
newnetflix_df=netflix_df.drop['Type']
netnetflix_df.head()

TypeError: 'method' object is not subscriptable

In [18]:
netflix_df.head())

SyntaxError: unmatched ')' (<ipython-input-18-44437995d582>, line 1)